- name: Fix ip/hostname change related problems
  script: fixhostname.sh

- name: create cinder loopback device
  shell: losetup -f /opt/stack/data/stack-volumes-backing-file

- name: start devstack screen session
  shell: cd /home/stack/devstack && su stack -c 'screen -d -m -c stack-screenrc'
